[changelog]
header = ""
body = """
{% if version %}
## [{{ version | trim_start_matches(pat="v") }}](https://github.com/samzong/confer/compare/{{ previous.version }}...{{ version }}) ({{ timestamp | date(format="%Y-%m-%d") }})
{% for group, commits in commits | group_by(attribute="group") %}

### {{ group | striptags | trim }}
{% for commit in commits %}
* {% if commit.scope %}**{{ commit.scope }}:** {% endif %}{{ commit.message }}{% endfor %}
{% endfor %}
{% endif %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
require_conventional = true
protect_breaking_commits = true
commit_preprocessors = [
  { pattern = '\(#(\d+)\)', replace = "([#${1}](https://github.com/samzong/confer/issues/${1}))" },
]
commit_parsers = [
  { message = "^chore\\(release\\)", skip = true },
  { message = "^Merge ", skip = true },
  { message = "^[a-z]+(\\(.+\\))?!:", group = "<!-- 0 -->⚠ BREAKING CHANGES" },
  { message = "^feat", group = "<!-- 1 -->Features" },
  { message = "^fix", group = "<!-- 2 -->Fixes" },
  { message = "^perf", group = "<!-- 3 -->Performance" },
  { message = "^refactor", group = "<!-- 4 -->Refactors" },
  { message = "^docs", group = "<!-- 5 -->Documentation" },
  { message = "^chore|^ci|^build|^test", skip = true },
]
tag_pattern = "^v[0-9]+\\.[0-9]+\\.[0-9]+$"
sort_commits = "oldest"
